sonar.projectKey=mlops-test-image-details
sonar.projectName=MLOps Test - Image Details

sonar.sources=app
sonar.tests=tests

sonar.python.version=3.11

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=junit.xml

sonar.exclusions=**/__pycache__/**,**/*.pyc